name: deploy
on:
    push:
        branches:
            - main
permissions:
    contents: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # fetch all commits/branches
            - name: Configure Git Credentials
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - run: |
                  echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
                  echo "PACKAGE_VERSION=$(cat config.json | jq .version)" >> $GITHUB_ENV
            - uses: actions/cache@v4
              with:
                  key: mkdocs-material-${{ env.cache_id }}
                  path: .cache
                  restore-keys: |
                      mkdocs-material-
            - run: |
                  pip install mkdocs-material
                  pip install mike
            - run: |
                  echo $PACKAGE_VERSION
                  mike deploy --push --update-aliases $PACKAGE_VERSION latest
